### ISSUE TITLE
Is there a way to instantiate 2 copies of this or have settings NOT be global?

### ISSUE THREAD

**Issue by sangkong** [tsbkelly/Streamdeck-Midibutton#2]
Currently, an installation of this only can control 1 device. I'd like to use this to control multiple devices. I tried creating a new instance of the button, but it doesn't seem to work with 2 instantiations of the plugin with the various properties changed.

**Comment by tsbkelly** [comment]
Hi,

This isn't currently possible, due to the architecture of the Streamdeck plugins. I'll have a look at changing the plugin so each button can control a different MIDI port, but it won't be for a while, I'm afraid. In the meantime could you use different MIDI channels to achieve the same result?

Cheers
